
CREATE TABLE IF NOT EXISTS usuaris (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(300) NOT NULL,
    email VARCHAR(50) NOT NULL,
    nom VARCHAR(30) NOT NULL,
    cognoms VARCHAR(30) NOT NULL,
    dataNaixement DATE,
    sexe VARCHAR(1),
    rol VARCHAR(30),
    estatCivil VARCHAR(30),
    carnetConduir VARCHAR(30),
    codiPostal VARCHAR(30),
    poblacio VARCHAR(30),
    provincia VARCHAR(30),
    pais VARCHAR(30),
    carrer VARCHAR(30),
    numero VARCHAR(30),
    dataCreacio TIMESTAMP
);
CREATE TABLE IF NOT EXISTS telefons (
    telefonId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    telefonNumero VARCHAR(30) NOT NULL,
    telefonTipus VARCHAR(30) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    dataCreacio TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS emails ( emailId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(30) NOT NULL, emailTipus VARCHAR(30) NOT NULL, userId INT(6) UNSIGNED NOT NULL, dataCreacio TIMESTAMP, FOREIGN KEY (userId) REFERENCES usuaris(id) );

CREATE TABLE IF NOT EXISTS habilitats (
    habilitatId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    habilitatValor VARCHAR(80) NOT NULL,
    habilitatNivell INT NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    dataCreacio TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);


CREATE TABLE IF NOT EXISTS idiomes (
    idiomaId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idiomaNom VARCHAR(50) NOT NULL,
    idiomaNivell INT NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS competencies (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    valor VARCHAR(50) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS informatica (
    informaticaId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    informaticaNom VARCHAR(50) NOT NULL,
    informaticaNivell INT NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS experiencies (
    experienciaId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    experienciaDataInici VARCHAR(50) NOT NULL,
    experienciaDataFi VARCHAR(50) NOT NULL,
    experienciaTitol VARCHAR(50) NOT NULL,
    experienciaEmpresa VARCHAR(50) NOT NULL,
    experienciaUbicacio VARCHAR(50) NOT NULL,
    experienciaDescripcio VARCHAR(500) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS estudis (
    estudiId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    estudiDataInici VARCHAR(50) NOT NULL,
    estudiDataFi VARCHAR(50) NOT NULL,
    estudiTitol VARCHAR(50) NOT NULL,
    estudiEmpresa VARCHAR(50) NOT NULL,
    estudiUbicacio VARCHAR(50) NOT NULL,
    estudiDescripcio VARCHAR(500) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS cursos (
    cursId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cursDataInici VARCHAR(50) NOT NULL,
    cursDataFi VARCHAR(50) NOT NULL,
    cursTitol VARCHAR(50) NOT NULL,
    cursEmpresa VARCHAR(50) NOT NULL,
    cursUbicacio VARCHAR(50) NOT NULL,
    cursDescripcio VARCHAR(500) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS projectes (
    projecteId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    projecteDataInici VARCHAR(50) NOT NULL,
    projecteDataFi VARCHAR(50) NOT NULL,
    projecteTitol VARCHAR(50) NOT NULL,
    projecteEmpresa VARCHAR(50) NOT NULL,
    projecteUbicacio VARCHAR(50) NOT NULL,
    projecteDescripcio VARCHAR(500) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS interessos (
    interesId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    interesNom VARCHAR(50) NOT NULL,
    interesDescripcio VARCHAR(500) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS cvs (
    cvId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cvNom VARCHAR(50) NOT NULL,
    cvPerfil VARCHAR(500) NOT NULL,
    cvDataCreacio VARCHAR(50) NOT NULL,
    cvDataModificacio VARCHAR(50) NOT NULL,
    userId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (userId) REFERENCES usuaris(id)
);
CREATE TABLE IF NOT EXISTS cvHabilitats (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    originalData INT(6) UNSIGNED NOT NULL,
    cvId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (cvId) REFERENCES cvs(cvId)  ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (originalData) REFERENCES habilitats(habilitatId) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS cvIdiomes (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    originalData INT(6) UNSIGNED NOT NULL,
    cvId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (cvId) REFERENCES cvs(cvId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (originalData) REFERENCES idiomes(idiomaId) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS cvInformatica(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    originalData INT(6) UNSIGNED NOT NULL,
    cvId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (cvId) REFERENCES cvs(cvId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (originalData) REFERENCES informatica(informaticaId) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS cvEstudis(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    originalData INT(6) UNSIGNED NOT NULL,
    cvId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (cvId) REFERENCES cvs(cvId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (originalData) REFERENCES estudis(estudiId) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS cvExperiencies(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    originalData INT(6) UNSIGNED NOT NULL,
    cvId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (cvId) REFERENCES cvs(cvId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (originalData) REFERENCES experiencies(experienciaId) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS cvCompetencies(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    originalData INT(6) UNSIGNED NOT NULL,
    cvId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (cvId) REFERENCES cvs(cvId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (originalData) REFERENCES competencies(id) ON DELETE CASCADE ON UPDATE CASCADE
);
